name: rl-scanner

on:
  workflow_call:
    inputs:
      artifact-path:
        description: "Path to the artifact to be scanned."
        type: string
        required: true
      version:
        description: "Version of the artifact."
        type: string
        required: true
      runner:
        description: "Desired runner to execute on"
        required: false
        default: "ubuntu-latest"
        type: string
    secrets:
      RLSECURE_LICENSE:
        description: "License key for ReversingLabs scanner."
        required: true
      RLSECURE_SITE_KEY:
        description: "Site key for ReversingLabs scanner."
        required: true
      SIGNAL_HANDLER_TOKEN:
        description: "Used to submit scan event telemetry."
        required: true
      SIGNAL_HANDLER_DOMAIN:
        description: "Domain for the signal handler endpoint."
        required: true
      PRODSEC_TOOLS_ARN:
        description: "ARN for ProdSec tools AWS role."
        required: true
      PRODSEC_TOOLS_USER:
        description: "User for ProdSec Python tools repo."
        required: true
      PRODSEC_TOOLS_TOKEN:
        description: "Token for ProdSec Python tools repo."
        required: true
      PRODSEC_PYTHON_TOOLS_REPO:
        description: "URL for ProdSec Python tools repo."
        required: true
    outputs:
      scan-status:
        description: "The outcome of the scan process."
        value: ${{ jobs.rl-scan.outputs.scan-status }}

jobs:
  rl-scan:
    runs-on:
      labels: ${{ inputs.runner }}
    steps:
      - name: Run RL Scanner
        id: scan
        uses: auth0/devsecops-tooling/.github/actions/rl-scan@main
        with:
          artifact-path: ${{ inputs.artifact-path }}
          version: ${{ inputs.version }}
          RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
          SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
          SIGNAL_HANDLER_DOMAIN: ${{ secrets.SIGNAL_HANDLER_DOMAIN }}
          PRODSEC_TOOLS_ARN: ${{ secrets.PRODSEC_TOOLS_ARN }}
          PRODSEC_TOOLS_USER: ${{ secrets.PRODSEC_TOOLS_USER }}
          PRODSEC_TOOLS_TOKEN: ${{ secrets.PRODSEC_TOOLS_TOKEN }}
          PRODSEC_PYTHON_TOOLS_REPO: ${{ secrets.PRODSEC_PYTHON_TOOLS_REPO }}
    outputs:
      scan-status: ${{ steps.scan.outputs.scan-status }}