name: test

on:
  pull_request_target:
    branches:
      - main
jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      runner: ubuntu-latest
    secrets: inherit
